export const GET_CURRENT_INTERLOCUTOR: string = 'GET_CURRENT_INTERLOCUTOR';
export const REMOVE_CURRENT_INTERLOCUTOR: string = 'REMOVE_CURRENT_INTERLOCUTOR';
export const GET_INTERLOCUTORS: string = 'GET_INTERLOCUTORS';
export const APP_INTERLOCUTOR: string = 'APP_INTERLOCUTOR';
export const SET_INTERLOCUTORS: string = 'SET_INTERLOCUTORS';
export const REMOVE_INTERLOCUTOR: string = 'REMOVE_INTERLOCUTOR';
export const REMOVE_INTERLOCUTORS: string = 'REMOVE_INTERLOCUTORS';
export const UPDATE_INTERLOCUTOR: string = 'UPDATE_INTERLOCUTOR';

