export const GET_CURRENT_INTERLOCUTOR: string = 'GET_CURRENT_INTERLOCUTOR';
export const REMOVE_CURRENT_INTERLOCUTOR: string = 'REMOVE_CURRENT_INTERLOCUTOR';
export const GET_INTERLOCUTORS: string = 'GET_INTERLOCUTORS';
export const APP_INTERLOCUTOR: string = 'APP_INTERLOCUTOR';
export const SET_INTERLOCUTORS: string = 'SET_INTERLOCUTORS';
export const REMOVE_INTERLOCUTOR: string = 'REMOVE_INTERLOCUTOR';
export const UPDATE_INTERLOCUTOR: string = 'UPDATE_INTERLOCUTOR';
export const SET_CURRENT_INTERLOCUTOR_MEDIA_CONTROL: string = 'SET_CURRENT_INTERLOCUTOR_MEDIA_CONTROL';
export const SET_MEDIA_STREAM_CURRENT_INTERLOCUTOR: string = 'SET_MEDIA_STREAM_CURRENT_INTERLOCUTOR';
export const SET_PEER_CONNECTION_INTERLOCUTOR: string = 'SET_PEER_CONNECTION_INTERLOCUTOR';

